name: Build TODO-App

on:
  schedule:
    # Run Sunday at 6:00 AM UTC
    - cron: "0 6 * * 0"

  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - '*.csproj'
    - '**.cs'
    - '.github/workflows/TODO.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/retaildevcrews/TODO
      LOAD_TEST_REPO: ghcr.io/retaildevcrews/TODO

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Docker Build
      run: |
        docker build . --progress auto -t image

    - name: Docker Run and Test
      run: |
           
            docker run --rm -d --name in-memory -p 8080:8080 image --in-memory

            echo "Waiting for web server to start ..."
        
            wait_time=10        
            sleep $wait_time

            # wait up to 30 seconds for web server to start
            while true
            do
                if curl localhost:8080/version ; then
                    echo -e "\n web server is running"
                    break
                fi
                if [ $wait_time -gt 30 ] ; then
                  echo -e "\n timeout waiting for web server to start"
                  exit 1
                fi
                
                sleep 1
                ((wait_time=wait_time+1))
            done

            docker run --rm --network=host ghcr.io/retaildevcrews/$LOAD_TEST_REPO:TODO -s "http://localhost:8080" --max-errors 1 -f baseline.json
        
    - name: Docker Tag and Push
      run: |
        VERSION=$(docker run --rm image --version)
        # tag the repo with :TODO
        docker tag image $DOCKER_REPO:TODO
        # Push to the repo
        docker push -a $DOCKER_REPO
